#SECRET , YOU CAN SEE USERNAME AND PASSWORD ARE MAPPED IN MONGO.YML 
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU= 
  mongo-root-password: cGFzc3dvcmQ=
